[2024-02-01T08:39:42.799+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: hola_mundo.print_hello_task manual__2024-02-01T08:39:05.197095+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-02-01T08:39:42.798993+00:00 and task will be retried at 2024-02-01T08:44:22.365920+00:00.
[2024-02-01T08:39:42.882+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-02-01T08:44:35.348+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hola_mundo.print_hello_task manual__2024-02-01T08:39:05.197095+00:00 [queued]>
[2024-02-01T08:44:35.557+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hola_mundo.print_hello_task manual__2024-02-01T08:39:05.197095+00:00 [queued]>
[2024-02-01T08:44:35.558+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-02-01T08:44:35.694+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): print_hello_task> on 2024-02-01 08:39:05.197095+00:00
[2024-02-01T08:44:35.768+0000] {standard_task_runner.py:60} INFO - Started process 250 to run task
[2024-02-01T08:44:35.789+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hola_mundo', 'print_hello_task', 'manual__2024-02-01T08:39:05.197095+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/prueba.py', '--cfg-path', '/tmp/tmp5muivvhd']
[2024-02-01T08:44:35.807+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask print_hello_task
[2024-02-01T08:44:36.235+0000] {task_command.py:423} INFO - Running <TaskInstance: hola_mundo.print_hello_task manual__2024-02-01T08:39:05.197095+00:00 [running]> on host d65f2c38c452
[2024-02-01T08:44:36.975+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='guille' AIRFLOW_CTX_DAG_ID='hola_mundo' AIRFLOW_CTX_TASK_ID='print_hello_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T08:39:05.197095+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-01T08:39:05.197095+00:00'
[2024-02-01T08:44:37.034+0000] {logging_mixin.py:188} INFO - Hola Mundo!
[2024-02-01T08:44:37.035+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-01T08:44:37.155+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=hola_mundo, task_id=print_hello_task, execution_date=20240201T083905, start_date=20240201T084435, end_date=20240201T084437
[2024-02-01T08:44:37.341+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-01T08:44:37.656+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
