[2024-02-26T08:40:13.853+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hola_mundo.print_bye_task scheduled__2024-02-25T00:00:00+00:00 [queued]>
[2024-02-26T08:40:13.899+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hola_mundo.print_bye_task scheduled__2024-02-25T00:00:00+00:00 [queued]>
[2024-02-26T08:40:13.900+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-26T08:40:14.020+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): print_bye_task> on 2024-02-25 00:00:00+00:00
[2024-02-26T08:40:14.045+0000] {standard_task_runner.py:60} INFO - Started process 86 to run task
[2024-02-26T08:40:14.098+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hola_mundo', 'print_bye_task', 'scheduled__2024-02-25T00:00:00+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/prueba.py', '--cfg-path', '/tmp/tmpnpj6ckfc']
[2024-02-26T08:40:14.107+0000] {standard_task_runner.py:88} INFO - Job 134: Subtask print_bye_task
[2024-02-26T08:40:14.532+0000] {task_command.py:423} INFO - Running <TaskInstance: hola_mundo.print_bye_task scheduled__2024-02-25T00:00:00+00:00 [running]> on host d65f2c38c452
[2024-02-26T08:40:14.999+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='guille' AIRFLOW_CTX_DAG_ID='hola_mundo' AIRFLOW_CTX_TASK_ID='print_bye_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-25T00:00:00+00:00'
[2024-02-26T08:40:15.004+0000] {logging_mixin.py:188} INFO - Adios Mundo!
[2024-02-26T08:40:15.005+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-26T08:40:15.031+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=hola_mundo, task_id=print_bye_task, execution_date=20240225T000000, start_date=20240226T084013, end_date=20240226T084015
[2024-02-26T08:40:15.094+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-26T08:40:15.151+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
