[2024-02-29T07:37:54.983+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hola_mundo.print_bye_task scheduled__2024-02-28T00:00:00+00:00 [queued]>
[2024-02-29T07:37:55.003+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hola_mundo.print_bye_task scheduled__2024-02-28T00:00:00+00:00 [queued]>
[2024-02-29T07:37:55.003+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-29T07:37:55.035+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): print_bye_task> on 2024-02-28 00:00:00+00:00
[2024-02-29T07:37:55.042+0000] {standard_task_runner.py:60} INFO - Started process 82 to run task
[2024-02-29T07:37:55.049+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hola_mundo', 'print_bye_task', 'scheduled__2024-02-28T00:00:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/prueba.py', '--cfg-path', '/tmp/tmp07nivif2']
[2024-02-29T07:37:55.055+0000] {standard_task_runner.py:88} INFO - Job 157: Subtask print_bye_task
[2024-02-29T07:37:55.149+0000] {task_command.py:423} INFO - Running <TaskInstance: hola_mundo.print_bye_task scheduled__2024-02-28T00:00:00+00:00 [running]> on host d65f2c38c452
[2024-02-29T07:37:55.297+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='guille' AIRFLOW_CTX_DAG_ID='hola_mundo' AIRFLOW_CTX_TASK_ID='print_bye_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-28T00:00:00+00:00'
[2024-02-29T07:37:55.300+0000] {logging_mixin.py:188} INFO - Adios Mundo!
[2024-02-29T07:37:55.301+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-29T07:37:55.317+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=hola_mundo, task_id=print_bye_task, execution_date=20240228T000000, start_date=20240229T073754, end_date=20240229T073755
[2024-02-29T07:37:55.380+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-29T07:37:55.410+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
